-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "createAt" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "deadlineAt" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updateAt" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "updateAt" SET DATA TYPE TIMESTAMPTZ(0);
